### ISSUE TITLE
Get General Help

### ISSUE THREAD

**Issue by hotsu0p** [BestGamersH/Multipurpose-Discord-Bot#13]
## **What's your nodejs Version.**
Show the output of: `node -v`
v18.18.0

## **What's the version you downloaded the bot?**
From the releases e.g.: latest

## **Desktop (please complete the following information):**
> - OS: windows 11
> - Version latest

## **Additional context, text and screenshots!**
> Add any other context about the problem here.

can you guide me though installing?

**Comment by BestGamersH** [comment]
DM me on discord,  username bestgamershk
