### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Imbossplay** [BestGamersH/Multipurpose-Discord-Bot#2]
the youtubetogether command when using it says that the discord does not have permissions when I have set all the permissions

**Comment by BestGamersH** [comment]
That's not the bot's permissions.
That's the server or your id problem as probably its not registered for youtube together that is in beta now.
Follow these steps: 
Step 1: Open YouTube and select the video you want to watch with friends.
Step 2: Open Discord and join a channel to start streaming the video. 
Step 3: Then look for 'Screen' and click on it.
Step 4: Then select the window that you want to watch with your friends. 
Step 5: Make sure that the 'Sound' toggle button is switched on.
Step 6: Then click 'Go Live'.
Step 7: The video is available to watch. Now, send an Invite to your friends to watch the video together.

**Comment by AwesomePerson2** [comment]
@BestGamersH  be smart its a error in the code
