### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SLucifer74** [BestGamersH/Multipurpose-Discord-Bot#4]
Welcome to SERVICE HANDLER /--/ By   /--/ Discord: BestGamersHK#9999
[x] :: Now loading the Commands ...
[x] :: LOADED THE 630 COMMANDS after: 35776ms
[x] :: Now loading the Database...
[x] :: LOADED THE DATABASES after: 180ms
[x] :: Now loading the Events ...
[x] :: LOADED THE 15 EVENTS after: 15ms

     ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
     ┃                                                                  ┃
     ┃ Logging into the BOT...                                          ┃
     ┃                                                                  ┃
     ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Provided token: //////////////////////////.**************************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 987
[WS => Manager] Using the recommended shard count provided by Discord: 1
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 9
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] Took 288ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 14335
[WS => Shard 0] Clearing the heartbeat interval.
[WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSED
[WS => Shard 0] WS State: CLOSED
[WS => Shard 0] [WebSocket] Adding a WebSocket close timeout to ensure a correct WS reconnect.
        Timeout: 5000ms
[WS => Shard 0] [CLOSE]
    Event Code: 4014
    Clean     : true
    Reason    : Disallowed intent(s).
 || <==> || [Sun Nov 13 2022 19:00:29] || <==> || Shard #0 Disconnected || <==> ||
[WS => Shard 0] DISALLOWED_INTENTS
[WS => Manager] Manager was destroyed. Called by:
Error [MANAGER_DESTROYED]: Manager was destroyed.
    at WebSocketManager.destroy (C:\Users\sabas\Desktop\Workplace\Multipurpose-Discord-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:317:54)
    at Client.destroy (C:\Users\sabas\Desktop\Workplace\Multipurpose-Discord-Bot-main\node_modules\discord.js\src\client\Client.js:284:13)
    at Client.login (C:\Users\sabas\Desktop\Workplace\Multipurpose-Discord-Bot-main\node_modules\discord.js\src\client\Client.js:257:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSED

=== UNHANDLED REJECTION ===
Reason:  Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\sabas\Desktop\Workplace\Multipurpose-Discord-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:245:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.login (C:\Users\sabas\Desktop\Workplace\Multipurpose-Discord-Bot-main\node_modules\discord.js\src\client\Client.js:254:7)
=== UNHANDLED REJECTION ===

[WS => Shard 0] [WebSocket] Clearing the close timeout.
[WS => Shard 0] [WebSocket] Close Emitted: false
[WS => Shard 0] [WebSocket] did not close properly, assuming a zombie connection.
Emitting close and reconnecting again.
[WS => Shard 0] [CLOSE]
    Event Code: 1011
    Clean     : false
    Reason    : INTERNAL_ERROR
 || <==> || [Sun Nov 13 2022 19:00:34] || <==> || Shard #0 Reconnecting || <==> ||

**Comment by hackern88** [comment]
Same prob
