### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 09JK** [BestGamersH/Multipurpose-Discord-Bot#49]
## **What's your nodejs Version.**
> V 18.19.0

## **What's the version you downloaded the bot?**
> i dont can find, so i think the latest. i downloaded today

## **Desktop (please complete the following information):**
> - OS: Debian
> - Version: 12

## **Describe the bug**
> The Error "Cannot read properties of undefined (reading 'get')"

## **To Reproduce**
> Steps to reproduce the behavior e.g:
1. Execute a Command (it doesn't matter if its an command or not)
2. See error

## **Expected behavior**
> I want to test the bot so i installed it and than this happend

## **Additional context, text and screenshots!**
> ![image](https://github.com/BestGamersH/Multipurpose-Discord-Bot/assets/71210514/b78aceb8-2645-4fae-af15-ebc9ccc7a676)
> https://pastebin.com/rsbANAcK (we removed any private infos from our server)

**Comment by BestGamersH** [comment]
Use updated version, use node.js v18, have visual studio installed
